/**
 * Core TypeScript Type Definitions
 * Based on data-model.md entity definitions
 */

// ===== Enumerations =====

export enum EnrichmentStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  ENRICHED = 'ENRICHED',
  FAILED = 'FAILED',
  MANUAL_REVIEW = 'MANUAL_REVIEW',
}

export enum LeadTier {
  Hot = 'Hot',
  Warm = 'Warm',
  Cold = 'Cold',
  Unscored = 'Unscored',
}

// FR-025: Three persona types
export enum PersonaType {
  Exhibitor = 'Exhibitor',
  TargetCompany = 'TargetCompany',
  TargetPeople = 'TargetPeople',
}

// FR-027: Four report types
export enum ReportType {
  CROSummary = 'CROSummary',
  CompanySummary = 'CompanySummary',
  ContactSummary = 'ContactSummary',
  MergedReport = 'MergedReport',
}

export enum StorageAdapterType {
  LOCAL = 'LOCAL',
  MYSQL = 'MYSQL',
  HUBSPOT = 'HUBSPOT',
}

export enum FundingStage {
  Bootstrap = 'Bootstrap',
  Seed = 'Seed',
  SeriesA = 'Series A',
  SeriesB = 'Series B',
  SeriesCPlus = 'Series C+',
  Public = 'Public',
  PrivateEquity = 'Private Equity',
  Unknown = 'Unknown',
}

export type EmployeeRange = '1-10' | '11-50' | '51-200' | '201-500' | '501-1000' | '1001-5000' | '5001+'
export type RevenueRange = '<1M' | '1M-10M' | '10M-50M' | '50M-100M' | '100M-500M' | '500M-1B' | '1B+'

// ===== Core Entities =====

export interface BadgeScan {
  id: string
  eventId: string
  scannedAt: Date
  firstName?: string
  lastName?: string
  email?: string
  company: string
  jobTitle?: string
  phone?: string
  boothLocation?: string
  eventName: string
  notes?: string
  customFields?: Record<string, string>
  enrichmentStatus: EnrichmentStatus
  // FR-031: Proximity detection
  proximityGroupId?: string
  scannerId?: string
  // FR-032: Contact tier
  contactTier?: LeadTier
  createdAt: Date
  updatedAt: Date
}

export interface EnrichedCompany {
  id: string
  badgeScanId: string
  companyName: string
  domain?: string
  employeeCount?: number
  employeeRange?: EmployeeRange
  industry?: string
  industryCodes?: string[]
  annualRevenue?: number
  revenueRange?: RevenueRange
  techStack?: string[]
  fundingStage?: FundingStage
  totalFunding?: number
  headquarters?: string
  founded?: number
  description?: string
  linkedinUrl?: string
  twitterHandle?: string
  consensusMetadata: Record<string, ConsensusMetadata>
  enrichedAt: Date
  dataSource: string[]
  // FR-032: Company tier
  companyTier?: LeadTier
}

export interface ConsensusMetadata {
  fieldName: string
  consensusValue: unknown
  providerResponses: ProviderResponse[]
  agreementLevel: number
  confidence: 'High' | 'Medium' | 'Low'
  needsManualReview: boolean
}

export interface ProviderResponse {
  provider: string
  value: unknown
  confidence?: number
  responseTime: number
}

export interface Persona {
  id: string
  name: string
  description?: string
  // FR-025: Persona type
  type: PersonaType
  isDefault: boolean
  criteria: PersonaCriteria
  weights: PersonaWeights
  createdAt: Date
  updatedAt: Date
  createdBy?: string
  // FR-025: Auto-generation metadata for Exhibitor personas
  autoGenerated?: boolean
  websiteSource?: string
}

export interface PersonaCriteria {
  companySizeRange?: { min: number; max: number }
  industries?: string[]
  technologies?: string[]
  revenueRange?: { min: number; max: number }
  geographies?: string[]
  decisionMakerTitles?: string[]
  fundingStages?: FundingStage[]
}

export interface PersonaWeights {
  companySize: number
  industry: number
  technology: number
  revenue: number
  geography: number
  decisionMaker: number
  fundingStage: number
}

export interface PersonaMatch {
  id: string
  badgeScanId: string
  personaId: string
  fitScore: number
  tier: LeadTier
  criteriaMatches: CriteriaMatch[]
  actionableInsights?: string[]
  calculatedAt: Date
}

export interface CriteriaMatch {
  criterionName: string
  matched: boolean
  actualValue: unknown
  targetValue: unknown
  weight: number
  contributionToScore: number
}

export interface Report {
  id: string
  eventId: string
  name: string
  // FR-027: Report type
  reportType: ReportType
  filters?: ReportFilters
  generatedAt: Date
  badgeScanIds: string[]
  statistics: ReportStatistics
  exportedFormats?: ('CSV' | 'PDF' | 'CRO_SUMMARY' | 'COMPANY_REPORTS')[]
  // FR-028: Job tracking
  jobId?: string
}

export interface ReportFilters {
  tiers?: LeadTier[]
  industries?: string[]
  employeeRanges?: EmployeeRange[]
  revenueRanges?: RevenueRange[]
  technologies?: string[]
  personas?: string[]
  searchQuery?: string
  // FR-029: Tag filtering
  tags?: string[]
  // FR-030: List filtering
  lists?: string[]
}

export interface ReportStatistics {
  totalScans: number
  enrichedCount: number
  hotCount: number
  warmCount: number
  coldCount: number
  unscoredCount: number
  topIndustries: { industry: string; count: number }[]
  averageFitScore: number
  enrichmentSuccessRate: number
  // FR-032: Dual-tier statistics
  companyTierBreakdown?: {
    hot: number
    warm: number
    cold: number
    unscored: number
  }
  contactTierBreakdown?: {
    hot: number
    warm: number
    cold: number
    unscored: number
  }
  combinedTierBreakdown?: {
    hot: number
    warm: number
    cold: number
    unscored: number
  }
}

export interface Event {
  id: string
  name: string
  startDate?: Date
  endDate?: Date
  location?: string
  boothNumber?: string
  createdAt: Date
}

// FR-031: Proximity detection
export interface ProximityGroup {
  id: string
  eventId: string
  badgeScanIds: string[]
  detectedAt: Date
  timeWindowSeconds: number
  scannerId?: string
  boothLocation?: string
  confidence: 'LOW' | 'MEDIUM' | 'HIGH'
  associationType?: 'consultant' | 'joint_meeting' | 'transition' | 'unknown'
  needsReview: boolean
}

// FR-026: MEDDIC Qualification
export interface MEDDICScore {
  id: string
  badgeScanId: string
  companyId?: string
  // Six MEDDIC dimensions (0-100 scale)
  metricsScore: number
  economicBuyerScore: number
  decisionCriteriaScore: number
  decisionProcessScore: number
  identifyPainScore: number
  championScore: number
  // Overall qualification
  overallScore: number
  qualificationStatus: 'Qualified' | 'Developing' | 'Unqualified'
  // Identified decision makers
  economicBuyer?: {
    name?: string
    title?: string
    linkedinUrl?: string
    confidence: number
  }
  champion?: {
    name?: string
    title?: string
    linkedinUrl?: string
    confidence: number
  }
  missingDecisionMakers: Array<{
    role: string
    title: string
    foundViaResearch: boolean
    name?: string
    linkedinUrl?: string
  }>
  // Recommended engagement strategy
  engagementStrategy: string
  calculatedAt: Date
  calculatedBy?: string
}

// FR-029: Tag management
export interface Tag {
  id: string
  name: string
  color: string // Hex color code
  description?: string
  createdAt: Date
  createdBy?: string
}

// FR-030: List management
export interface List {
  id: string
  name: string
  description?: string
  type: 'static' | 'dynamic'
  // For static lists: manually added contact IDs
  badgeScanIds?: string[]
  // For dynamic lists: filter criteria
  filterCriteria?: ReportFilters
  contactCount: number
  lastUpdated: Date
  createdAt: Date
  createdBy?: string
}

// FR-028: Async report generation
export interface ReportJob {
  id: string
  reportId?: string // Set after report is generated
  eventId: string
  reportType: ReportType
  filters?: ReportFilters
  status: 'Queued' | 'Generating' | 'Completed' | 'Failed'
  progress: number // 0-100
  estimatedCompletionTime?: Date
  startedAt?: Date
  completedAt?: Date
  error?: string
  createdBy?: string
  notificationSent: boolean
}

// FR-032: Combined tier calculation
export interface CombinedTierCalculation {
  badgeScanId: string
  companyTier: LeadTier
  contactTier: LeadTier
  combinedTier: LeadTier
  companyTierScore: number // 0-100
  contactTierScore: number // 0-100
  combinedScore: number // Weighted: 60% company + 40% contact
  calculatedAt: Date
}

export interface StorageAdapterConfiguration {
  id: string
  adapterType: StorageAdapterType
  localStorageConfig?: LocalStorageConfig
  mysqlConfig?: MySQLConfig
  hubspotConfig?: HubSpotConfig
  isActive: boolean
  lastTestedAt?: Date
  createdAt: Date
  updatedAt: Date
}

export interface LocalStorageConfig {
  dataDirectory: string
}

export interface MySQLConfig {
  host: string
  port: number
  database: string
  username: string
  password: string
  connectionPoolSize?: number
}

export interface HubSpotConfig {
  apiKey: string
  portalId: string
  customPropertyPrefix?: string
}

// ===== Utility Types =====

export interface ExportedData {
  badgeScans: BadgeScan[]
  enrichedCompanies: EnrichedCompany[]
  personas: Persona[]
  personaMatches: PersonaMatch[]
  reports: Report[]
  events: Event[]
  exportedAt: Date
  sourceAdapterType: StorageAdapterType
}

export interface EnrichmentJob {
  id: string
  eventId: string
  badgeScanIds: string[]
  status: 'pending' | 'processing' | 'completed' | 'failed'
  progress: number
  totalScans: number
  processedScans: number
  createdAt: Date
  completedAt?: Date
  error?: string
}

export interface CSVValidationError {
  row: number
  field: string
  whatFailed: string
  howToFix: string
  exampleFormat: string
}

// ===== API Response Types =====

// ===== API Response Types (3-part error format) =====

export interface APISuccessResponse<T = unknown> {
  success: true
  data: T
  message?: string
}

export interface APIErrorResponse {
  success: false
  error: {
    whatFailed: string
    howToFix: string
    exampleFormat?: string
    details?: unknown
  }
}

export type APIResponse<T = unknown> = APISuccessResponse<T> | APIErrorResponse

// Legacy type for compatibility
export interface ApiResponse<T = unknown> {
  success: boolean
  data?: T
  error?: {
    message: string
    code?: string
    details?: unknown
  }
}

export interface PaginatedResponse<T> {
  data: T[]
  total: number
  page: number
  pageSize: number
  hasMore: boolean
}

// ===== CSV Processing Types =====

export interface ColumnMapping {
  csvColumn: string
  targetField: keyof BadgeScan | 'customField'
  confidence: 'exact' | 'fuzzy' | 'position'
}

// Upload result for mapping preview (before confirmation)
export interface CSVUploadPreview {
  success: boolean
  headers: string[]
  sampleRows: Record<string, string>[]
  detectedMappings: ColumnMapping[]
  unmappedColumns: string[]
  confidence: 'high' | 'medium' | 'low'
  totalRows: number
  errors: CSVValidationError[]
}

// Final upload result after mapping confirmation
export interface CSVUploadResult {
  success: boolean
  scansImported: number
  scanIds: string[]
  eventId: string
  errors: CSVValidationError[]
  columnMappings: ColumnMapping[]
  duplicates?: Array<{
    newScanEmail: string
    duplicateCount: number
    existingScanIds: string[]
  }>
  // FR-031: Proximity detection results
  proximityGroupsDetected?: number
}

// ===== LLM and Enrichment Types =====

export type LLMProvider = 'Claude' | 'GPT-4' | 'Gemini' | 'Perplexity'

export interface EnrichmentResult {
  badgeScanId: string
  enrichedCompany?: EnrichedCompany
  personaMatches: PersonaMatch[]
  errors?: string[]
}

// ===== Export Format Types =====

export type ExportFormat = 'CSV' | 'PDF' | 'CRO_summary' | 'company_reports'

export interface CROSummary {
  executiveSummary: string
  topHotLeads: Array<{
    company: string
    contact: string
    fitScore: number
    keyInsights: string[]
  }>
  followUpPriorities: {
    hot: string[]
    warm: string[]
    cold: string[]
  }
}

export interface CompanyReport {
  companyProfile: {
    name: string
    domain?: string
    industry?: string
    employeeCount?: number
    revenue?: number
    headquarters?: string
  }
  personaMatchAnalysis: {
    fitScore: number
    tier: LeadTier
    criteriaBreakdown: CriteriaMatch[]
  }
  actionableInsights: {
    painPoints: string[]
    conversationStarters: string[]
  }
  tierJustification: string
}
